#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ContentControls.Resource", IsApplication=true)]

namespace ContentControls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hold = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int zoom_enter = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int zoom_exit = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int grey = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int lightgrey = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int listseparator = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int red = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int white = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int yellow = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Beach = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int map_pin = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Plants = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Seeds = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Shanghai = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int AutoCompleteInput = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int BackButton = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int ForwardButton = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int GoButton = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int Map = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int Menu = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int RunScriptButton = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int StopButton = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int Text1 = 2131165186;
			
			// aapt resource value: 0x7f070011
			public const int UrlText = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int Web = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int button = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int check1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int check2 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int radio1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int radio2 = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int spinner1 = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int star = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int textView1 = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int toggle1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int toggle2 = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AutoCompleteTextView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeSectionHeader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LightTheme = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MapView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NoGoogleMaps = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WebView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WebViewBrowser = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int WebViewInterop = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000b
			public const int ApplicationName = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int GoogleMapAPIKey = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int controls_1_checkbox_1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int controls_1_checkbox_2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int controls_1_radiobutton_1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int controls_1_radiobutton_2 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int controls_1_save = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int controls_1_star = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int listSeparatorTextViewStyle = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int textColorPrimary = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textColorSecondary = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textColorTertiary = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
