#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TablesAndCellStyles.Resource", IsApplication=true)]

namespace TablesAndCellStyles
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int lightgrey = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int listseparator = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Beach = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fastscroll_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Plants = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Seeds = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Shanghai = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int BigTextView = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int CalendarImageView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int DayTextView = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int Icon = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int List = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int Menu = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int MonthTextView = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int Text1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Text2 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int list_header_title = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int list_item_title = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DateListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GradientBackground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GradientBackgroundItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Header = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Home = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HomeSectionHeader = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ImageAndSubtitleItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LabelledSectionsIndexer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SectionListHeader = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SectionListItem = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomFastScroll = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
